### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by liuw5367** [liuw5367/chatgpt-asr-tts#1]
- [x] prompt 
- [x] 对话上下文
- [x] token限制
- [x] stream 滚动抖动问题
- [x] prompt 设置的情况下，允许直接发送
- [x] 消息的 prompt 展示优化
- [x] 错误提示优化
- [ ] 使用提示
- [ ] toast优化
- [ ] 列表中相邻的两个连续对话如何区分
- [ ] 列表中不连续的同一个对话如何能识别出来
- [ ] js 加载慢的问题
- [x] pwa
- [ ] 整理页面显示的文字

**Comment by liuw5367** [comment]
- [ ] stream 滚动抖动问题
- [ ] prompt 设置的情况下，允许直接发送
- [ ] 消息的 prompt 展示优化

**Comment by diemus** [comment]
还是很不错的，称得上高质量前端了，就是很多按钮图标没有提示做什么用的

**Comment by liuw5367** [comment]
> 还是很不错的，称得上高质量前端了，就是很多按钮图标没有提示做什么用的
> 
> 

这个有在考虑，应该怎么提示出来比较好。最近真是太忙了，能赶出来这些功能也挺不容易的。好像已经比较晚了，感觉这两天都没人发做的网页了 🤦‍♂️
chatgpt相关的网页看到的也很多了，但是有不少都挺不完善，页面也不协调，我也在需要思考怎么把它当成一个完整的产品做出来。
主要是这个网页自己是真的在用，还是有些动力做的好一点的😂

**Comment by diemus** [comment]
确实，功能大同小异。其实我一直想基于langchain做个插件系统，没想到openai自己做了
